### ISSUE TITLE
Docker Related

### ISSUE THREAD

**Issue by HaFred** [HaFred/dnn-rocket-accelerator#51]
https://www.linode.com/docs/guides/how-to-use-dockerfiles/

**Comment by HaFred** [comment]
## Docker CMDs
https://www.runoob.com/docker/docker-command-manual.html
`docker stop CONTAINER_NAMES`
`ps -elf | grep python` check ports

**Comment by HaFred** [comment]
The docker keeps on running this issue for DDP for a single node.
```
root@9d7ecac01d79:/Atlas# sh ./run_inference.sh 
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
fred: determine there is 2 gpu for this node
fred: determine there is 2 gpu for this node
Traceback (most recent call last):
  File "inference_spawn.py", line 222, in <module>
    main()
  File "inference_spawn.py", line 210, in main
    mp.spawn(main_worker(info_files, args),
  File "inference_spawn.py", line 138, in main_worker
    world_size=args.world_size, rank=args.rank)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 393, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 126, in _tcp_rendezvous_handler
    store = TCPStore(result.hostname, result.port, world_size, start_daemon, timeout)
RuntimeError: Address already in use
```
Seems like the docker container needs to communicate with the host if enabling two gpus. 
`docker run --gpus all -v $DOWNLOAD_PATH:/Atlas -it atlas-new` can only make it visible but not dealing with the communication for gpus. Needs to be settled individually.
Thus, we need to make Atlas outside the docker container. Since the cudatoolkit=10.2 should be ok on CUDA Version: 11.2.

**Comment by HaFred** [comment]
## Train Distributedly with Docker
https://leimao.github.io/blog/PyTorch-Distributed-Training/

**Comment by HaFred** [comment]
## A Great Docker Book
https://yeasy.gitbook.io/docker_practice/container/daemon
